module.exports = {
  "apiMessage": "This JSON was provided by Springer Nature",
  "query": "user experience",
  "apiKey": "72176eeb5c4422a35299b07dfb9bf04e",
  "result": [{ "total": "566851", "start": "1", "pageLength": "10", "recordsDisplayed": "10" }],
  "records": [{
    "contentType": "Chapter",
    "identifier": "doi:10.1007/978-3-319-01904-8_6-1",
    "url": [{ "format": "", "platform": "", "value": "http://dx.doi.org/10.1007/978-3-319-01904-8_6-1" }],
    "title": "Human-Centered Design and Smart Homes: How to Study and Design for the Home Experience?",
    "creators": [{ "creator": "Eggen, Berry" }, { "creator": "Hoven, Elise" }, { "creator": "Terken, Jacques" }],
    "publicationName": "Handbook of Smart Homes, Health Care and Well-Being",
    "openaccess": "false",
    "doi": "10.1007/978-3-319-01904-8_6-1",
    "publisher": "Springer",
    "publicationDate": "2021-01-01",
    "publicationType": "Book",
    "printIsbn": "",
    "electronicIsbn": "978-3-319-01904-8",
    "isbn": "",
    "genre": "ReviewPaper",
    "copyright": "©2021 Springer International Publishing Switzerland",
    "abstract": "The focus of this chapter is on designing for smart homes. The perspective will be user-driven design research. The chapter starts with a context analysis of the home environment. This analysis shows that, from a user perspective, home is about emotions and not about the physical house with all its smart applications. It is this “home experience” designers have to design for. The core of the chapter consists of the description of three big challenges that modern designers (need to) face when designing or studying smart home environments. These challenges are linked to existing and future design paradigms. The following challenges are addressed: (1) What makes a worthwhile user experience? (2) How to design for user experience? (3) How to design for user experiences that can be seamlessly integrated in everyday life? The chapter concludes with a summary of the main insights that emerge from current design research practice facing these challenges.",
  }, {
    "contentType": "Chapter",
    "identifier": "doi:10.1007/978-94-007-6994-6_15-1",
    "url": [{ "format": "", "platform": "", "value": "http://dx.doi.org/10.1007/978-94-007-6994-6_15-1" }],
    "title": "Design for the Value of Inclusiveness",
    "creators": [{ "creator": "Keates, Simeon" }],
    "publicationName": "Handbook of Ethics, Values, and Technological Design",
    "openaccess": "false",
    "doi": "10.1007/978-94-007-6994-6_15-1",
    "publisher": "Springer",
    "publicationDate": "2021-01-01",
    "publicationType": "Book",
    "printIsbn": "",
    "electronicIsbn": "978-94-007-6994-6",
    "isbn": "",
    "genre": "ReviewPaper",
    "copyright": "©2021 Springer Science+Business Media Dordrecht",
    "abstract": "There is an increasing awareness that many everyday products and services present challenges and difficulties to potential users. These difficulties may arise because the products and services have not been designed to allow for the full range of functional capabilities of the users who wish to use them. Medical conditions, accidents, ageing, or genetic predisposition means that most people will at some point experience functional impairments that make everyday products and services difficult to use. This chapter aims to introduce readers to the needs of the full range of users and provide an introduction to how they can develop more inclusive products and services. It addresses the principal approaches and tools to designing for inclusivity as well as the underlying rationale for why companies and designers need to consider this important set of users.",
  }, {
    "contentType": "Chapter",
    "identifier": "doi:10.1007/978-94-007-6994-6_10-1",
    "url": [{ "format": "", "platform": "", "value": "http://dx.doi.org/10.1007/978-94-007-6994-6_10-1" }],
    "title": "Design Methods in Design for Values",
    "creators": [{ "creator": "Vermaas, Pieter E." }, { "creator": "Hekkert, Paul" }, { "creator": "Manders-Huits, Noëmi" }, { "creator": "Tromp, Nynke" }],
    "publicationName": "Handbook of Ethics, Values, and Technological Design",
    "openaccess": "false",
    "doi": "10.1007/978-94-007-6994-6_10-1",
    "publisher": "Springer",
    "publicationDate": "2021-01-01",
    "publicationType": "Book",
    "printIsbn": "",
    "electronicIsbn": "978-94-007-6994-6",
    "isbn": "",
    "genre": "ReviewPaper",
    "copyright": "©2021 Springer Science+Business Media Dordrecht",
    "abstract": "In this chapter we demonstrate that contemporary design methodology provides methods for design for moral values. Subsequently, we explore the methodological challenges and problems that this brings to the table. First, we show that contemporary design methods are aimed at realizing values of users and society. These values are in general not moral ones yet do include in specific cases moral values. Second, we introduce a division between user-driven methods in which it are the users who introduce the values to be designed for and designer-driven methods in which the clients and designers are introducing these values. Third, we discuss two designer-driven design methods in detail for, respectively, design in general and social design in particular: the Vision in Product design method and the Social Implication Design method. Finally, we explore the challenges and problems of design for moral values with these and other design methods. We focus specifically on the designer who, once design is recognized as design for moral values, becomes responsible for the moral values the resulting products have. We argue that in this case the designer should make the moral values of products transparent to clients and users.",
  }, {
    "contentType": "Chapter",
    "identifier": "doi:10.1007/978-94-007-6994-6_14-1",
    "url": [{ "format": "", "platform": "", "value": "http://dx.doi.org/10.1007/978-94-007-6994-6_14-1" }],
    "title": "Design for the Value of Human Well-Being",
    "creators": [{ "creator": "Brey, Philip" }],
    "publicationName": "Handbook of Ethics, Values, and Technological Design",
    "openaccess": "false",
    "doi": "10.1007/978-94-007-6994-6_14-1",
    "publisher": "Springer",
    "publicationDate": "2021-01-01",
    "publicationType": "Book",
    "printIsbn": "",
    "electronicIsbn": "978-94-007-6994-6",
    "isbn": "",
    "genre": "ReviewPaper",
    "copyright": "©2021 Springer Science+Business Media Dordrecht",
    "abstract": "This chapter studies how and to what extent it is possible to design for well-being. Well-being is rarely considered in the design literature and is rarely linked to technology and design in philosophy and the social sciences. A few approaches to design for well-being have recently materialized, however, including Emotional Design, capability approaches, positive psychology approaches, and Life-Based Design. In this chapter, the notion of well-being will first be clarified and contemporary theories of and approaches to well-being will be reviewed. Next, theoretical and methodological issues in design for well-being will be discussed that must be accounted for in any successful approach. This will be followed by a review of the abovementioned four approaches to design for well-being. The chapter will conclude by considering open issues and future work in the development of design approaches for well-being.",
  }, {
    "contentType": "Chapter",
    "identifier": "doi:10.1007/978-94-007-6994-6_6-1",
    "url": [{ "format": "", "platform": "", "value": "http://dx.doi.org/10.1007/978-94-007-6994-6_6-1" }],
    "title": "Emotions in Design for Values",
    "creators": [{ "creator": "Desmet, Pieter M. A." }, { "creator": "Roeser, Sabine" }],
    "publicationName": "Handbook of Ethics, Values, and Technological Design",
    "openaccess": "false",
    "doi": "10.1007/978-94-007-6994-6_6-1",
    "publisher": "Springer",
    "publicationDate": "2021-01-01",
    "publicationType": "Book",
    "printIsbn": "",
    "electronicIsbn": "978-94-007-6994-6",
    "isbn": "",
    "genre": "ReviewPaper",
    "copyright": "©2021 Springer Science+Business Media Dordrecht",
    "abstract": "The contributions to this handbook show that technology is not value neutral, as is often thought. In this chapter, we argue that the inherent value-ladenness of technology evokes positive and negative emotions of the people who encounter or use it, by touching upon their personal and moral values. These emotions enable people to make concrete practical and moral judgments and to act accordingly. In this chapter, it is therefore proposed that emotions of users and designers alike should not be marginalized as being irrational and irrelevant, but instead be embraced as valuable gateways to values. Emotions reveal those values that matter to our well-being given a particular design or technology, and they are an important source of moral knowledge by being crucial to our capacity of moral reflection. This chapter discusses six sources of emotions in human-technology interaction and proposes how an understanding of user emotions can support design processes. In addition, the chapter discusses how emotions can resolve the lack of moral considerations in traditional approaches that assess the desirability of technology. It is argued that emotions do this by opening the gateway to moral considerations, such as responsibility, autonomy, risk, justice, and equity. This means that moral emotions can – and should – play an important role in the development of technology and can be considered to be indicators of success and failure in value-driven design processes.",
  }, {
    "contentType": "Chapter",
    "identifier": "doi:10.1007/978-3-319-02847-7_32-1",
    "url": [{ "format": "", "platform": "", "value": "http://dx.doi.org/10.1007/978-3-319-02847-7_32-1" }],
    "title": "Dashboard Display of Solar Weather",
    "creators": [{ "creator": "Tan, Su-Yin" }],
    "publicationName": "Handbook of Cosmic Hazards and Planetary Defense",
    "openaccess": "false",
    "doi": "10.1007/978-3-319-02847-7_32-1",
    "publisher": "Springer",
    "publicationDate": "2021-01-01",
    "publicationType": "Book",
    "printIsbn": "",
    "electronicIsbn": "978-3-319-02847-7",
    "isbn": "",
    "genre": "ReviewPaper",
    "copyright": "©2021 Springer International Publishing Switzerland",
    "abstract": "As society’s reliance on technological systems grows, so does our vulnerability to space weather. It is becoming increasingly important to be able to study and observe space weather and to predict events and conditions on the Sun and in near-Earth space. Timely delivery of space weather data and information enables us the ability to develop preventative or mitigating plans to reduce potentially harmful societal and economic impacts. The Space Weather Prediction Center (SWPC) is NOAA’s official source of space weather alerts, watches, and warnings. It is the primary warning center for the International Space Environment Services (ISES). The SWPC has a key role in providing real-time monitoring and forecasting of solar and geophysical events, exploring and evaluating new models and products, and overseeing their transition into operations. It maintains a website with a dashboard display for summarizing the vast amount of space weather data collected from numerous ground- and space-based systems. The purpose of this chapter is to review how digital dashboards have been effectively used by NASA and NOAA to visualize, communicate, and manage solar weather data for at-a-glance monitoring. In terms of information management, a digital dashboard is considered to be an easy to read, often single page, real-time user interface, enabling graphical presentation of data in a visual manner at a very high level. Such dashboards are becoming an integration of information management and decision support systems. This has proven to be a useful way of consolidating and displaying space weather products, as well as the preferred mode for the SWPC to relay summaries, warnings, and alerts to its user community. Dashboards are able to centralize information and offer users the ability to create customized views on a web-based interface. NOAA products can be readily displayed providing near- and long-term forecasts and trends related to geomagnetic storms, solar radiation storms, radio blackouts, and other solar events. For example, the SWPC dashboard provides near-real-time measurements from about 40 types of space weather operational products from GOES satellites, ground-based magnetometer measurements, and spacecraft, such as NASA’s ACE and NASA/ESA’s SOHO. The Community Coordinated Modeling Center (CCMC) is a multiagency partnership that provides the international research community with access to modern space science simulations. It is also responsible for developing advanced, online, visualization and analysis tools to facilitate a link between the research community and operational users and forecasters. The CCMC has developed dashboard systems, including the Space Weather Scoreboard, the Integrated Space Weather Analysis (iSWA), and the Database Of Notifications, Knowledge, and Information (DONKI). This chapter discusses some of the latest developments in dashboard displays for space weather monitoring and data dissemination. It first reviews the socioeconomic impact of space weather and the need for reliable communication and monitoring of solar observation data for the general public. Digital dashboards are described in general, as well as specific examples of how they are applied by NASA and NOAA for space weather data display. Examples of digital dashboards are reviewed including the iSWA and DONKI systems developed by the CCMC. Finally, the benefits and challenges of developing, implementing, and using digital dashboards for solar weather monitoring are discussed. In general, dashboard displays offer a robust and integrated system for providing information about past, present, and future space weather conditions. Providing a web-based interface, information enables public access to real-time imagery and information via the Internet and mobile devices. There are also a range of web tools available, enabling the user to customize the interface to suit unique data and forecasting requirements. Such technological developments encourage the continual availability and free exchange of space weather data and products worldwide for real-time forecasting and monitoring of space weather. Dashboard display and visualization tools support a multitude of planners and decision-makers for taking proactive measures to mitigate the impacts of potentially damaging space weather events.",
  }, {
    "contentType": "Chapter",
    "identifier": "doi:10.1007/978-3-319-01904-8_34-1",
    "url": [{ "format": "", "platform": "", "value": "http://dx.doi.org/10.1007/978-3-319-01904-8_34-1" }],
    "title": "Technology Acceptance by Patients: Empowerment and Stigma",
    "creators": [{ "creator": "Ziefle, Martina" }, { "creator": "Schaar, Anne Kathrin" }],
    "publicationName": "Handbook of Smart Homes, Health Care and Well-Being",
    "openaccess": "false",
    "doi": "10.1007/978-3-319-01904-8_34-1",
    "publisher": "Springer",
    "publicationDate": "2021-01-01",
    "publicationType": "Book",
    "printIsbn": "",
    "electronicIsbn": "978-3-319-01904-8",
    "isbn": "",
    "genre": "ReviewPaper",
    "copyright": "©2021 Springer International Publishing Switzerland",
    "abstract": "Given the increased life expectancy and considering shortcomings in the care sector, it is a fundamental challenge how older and frail people can be empowered to stay in their private home, keeping up mobility and independency for a longer time. The maturity of information and communication technology on the one hand and of medical technology on the other basically allows technology to take over the monitoring and care. However, so far, the inclusion of human factors and technology acceptance into a successful technology design is not adequately met. In the following, we describe relevant facets of technology empowerment and stigmas and the need to rethink traditional concepts. First, the requirements of adequate use and design of information and communication technologies in the medical field are addressed. Second, as the prevailing image of age is no longer adequate to the current demographic change, the need to rethink age and aging is described. Finally the need of user-centered design is discussed, followed by the need of a rethinking of the technology design process and the inclusion of potential users. The chapter ends with a discussion focused on requirements of patient empowerment to reflect all the aforementioned aspects from a patient’s point of view.",
  }, {
    "contentType": "Chapter",
    "identifier": "doi:10.1007/978-94-007-6994-6_33-1",
    "url": [{ "format": "", "platform": "", "value": "http://dx.doi.org/10.1007/978-94-007-6994-6_33-1" }],
    "title": "Participatory Design and Design for Values",
    "creators": [{ "creator": "Velden, Maja" }, { "creator": "Mörtberg, Christina" }],
    "publicationName": "Handbook of Ethics, Values, and Technological Design",
    "openaccess": "false",
    "doi": "10.1007/978-94-007-6994-6_33-1",
    "publisher": "Springer",
    "publicationDate": "2021-01-01",
    "publicationType": "Book",
    "printIsbn": "",
    "electronicIsbn": "978-94-007-6994-6",
    "isbn": "",
    "genre": "ReviewPaper",
    "copyright": "©2021 Springer Science+Business Media Dordrecht",
    "abstract": "Participatory Design (PD) is a design methodology in which the future users of a design participate as co-designers in the design process. It is a value-centered design approach because of its commitment to the democratic and collective shaping of a better future. This chapter builds forth on the Scandinavian Participatory Design tradition. We discuss why the design process is as important as the final result, the product, or service. The creative application of Participatory Design methods facilitates a design process in which values emerge and become inscribed in a prototype. We present PD’s guiding principles: equalizing power relations, democratic practices, situation-based action, mutual learning, tools and techniques, and alternative visions about technology. In addition, we discuss some value practices and design methods informed by our PD projects in health care and the public sector. We maintain that Participatory Design increases the chance that the final result of a design process represents the values of the future users.",
  }, {
    "contentType": "Chapter",
    "identifier": "doi:10.1007/978-3-319-01904-8_3-1",
    "url": [{ "format": "", "platform": "", "value": "http://dx.doi.org/10.1007/978-3-319-01904-8_3-1" }],
    "title": "A Framework for the Acceptance of Gerontechnology in Relation to Smart Living",
    "creators": [{ "creator": "Bouwhuis, Don G." }],
    "publicationName": "Handbook of Smart Homes, Health Care and Well-Being",
    "openaccess": "false",
    "doi": "10.1007/978-3-319-01904-8_3-1",
    "publisher": "Springer",
    "publicationDate": "2021-01-01",
    "publicationType": "Book",
    "printIsbn": "",
    "electronicIsbn": "978-3-319-01904-8",
    "isbn": "",
    "genre": "ReviewPaper",
    "copyright": "©2021 Springer International Publishing Switzerland",
    "abstract": "Despite the wide availability of telecare devices, the economic pressures, and the claimed benefits, the uptake of telecare services by older people is disappointingly limited. Much research is spent on finding out why the telecare acceptance is so much less than expected. Ease of use, or rather lack of it – a seemingly likely cause – is difficult to assess since the traditional usability criteria do not apply well to the daily life of older people. Acceptance in the social environment plays an important role, sometimes in a positive sense, but mostly in a negative one; however, social environment is all but impossible to manipulate. What does delay acceptance is the lack of standardization, which, in turn is also due to the fact that the impressive technological progress of the past decades has largely bypassed the field of assistive technology and health care. Another negative factor is cost. Though the price of devices has come down appreciably in recent years, system architecture and installation are getting more expensive and increased functionality goes hand in hand with higher cost. Next, during the actual running of telecare systems, successful operation has to compete with inherent difficulties of decision making in a noisy context. Making correct diagnoses is necessarily connected with false alarms, which may render the telecare system unusable. This is exacerbated by sources of unreliability in the system as a whole, like falling sensors, disconnected leads, empty batteries, and erased memories. In the light of these difficulties, traditional Technology Acceptance Models (TAMs) are focusing on a very small part and then probably the wrong one of the whole complex multistage decision process in implementing a telecare system. As it is, the comparatively immature state of telecare systems is up to now a multisectoral issue, in which stakeholders of different economic sectors operate mostly independently. Early stakeholders take decisions which later ones have to accept, up to the client as the end user, who also has to accept, but often does not. In a confusing situation like this, where the client is confronted with a system he or she has not chosen, it is doubtful that models based on a theory of rational behavior like the TAMs or Innovation Theory are valid at all. What should be minimally done on the basis of these observations are three things. First, an effective business case should be developed to run a telecare system – currently absent. Second, in addition to regulation, there should be a strong effort in the area of standardization. Finally, telecare should become a product that older people want, not one they have to accept.",
  }, {
    "contentType": "Chapter",
    "identifier": "doi:10.1007/978-94-007-6994-6_9-1",
    "url": [{ "format": "", "platform": "", "value": "http://dx.doi.org/10.1007/978-94-007-6994-6_9-1" }],
    "title": "Mediation in Design for Values",
    "creators": [{ "creator": "Spahn, A." }],
    "publicationName": "Handbook of Ethics, Values, and Technological Design",
    "openaccess": "false",
    "doi": "10.1007/978-94-007-6994-6_9-1",
    "publisher": "Springer",
    "publicationDate": "2021-01-01",
    "publicationType": "Book",
    "printIsbn": "",
    "electronicIsbn": "978-94-007-6994-6",
    "isbn": "",
    "genre": "ReviewPaper",
    "copyright": "©2021 Springer Science+Business Media Dordrecht",
    "abstract": "Mediation is the claim that technologies have an impact on the way in which we perceive the world and on the way we act in it. Often this impact goes beyond human intentions: it can hardly be understood only in terms of “intentions of the user” or in terms of “intentions of the designer.” Mediation argues that technologies have “agency” themselves and then tries to explicate the way in which technological objects and human subjects form a complex relation and constitute each other. Designers should anticipate mediation effects and can use mediation to moralize technologies. However, questions can be asked about how far the moralizing of technologies is compatible with user autonomy.",
  }],
  "facets": [{
    "name": "subject",
    "values": [{ "value": "Medicine & Public Health", "count": "150937" }, {
      "value": "Computer Science",
      "count": "93829",
    }, { "value": "Engineering", "count": "51985" }, {
      "value": "User Interfaces and Human Computer Interaction",
      "count": "42023",
    }, { "value": "Life Sciences", "count": "40146" }, {
      "value": "Public Health",
      "count": "39655",
    }, { "value": "Biomedicine", "count": "39186" }, {
      "value": "Medicine/Public Health, general",
      "count": "39158",
    }, {
      "value": "Information Systems Applications (incl. Internet)",
      "count": "35139",
    }, {
      "value": "Artificial Intelligence (incl. Robotics)",
      "count": "32685",
    }, { "value": "Computer Communication Networks", "count": "30214" }, {
      "value": "Internal Medicine",
      "count": "24995",
    }, { "value": "Business and Management", "count": "24032" }, {
      "value": "Oncology",
      "count": "20588",
    }, { "value": "Neurosciences", "count": "19416" }, {
      "value": "Education",
      "count": "18405",
    }, {
      "value": "Computational Intelligence",
      "count": "18065",
    }, {
      "value": "Science, Humanities and Social Sciences, multidisciplinary",
      "count": "17624",
    }, { "value": "Psychiatry", "count": "17588" }, { "value": "Information Storage and Retrieval", "count": "17551" }],
  }, {
    "name": "keyword",
    "values": [{ "value": "Quality of life", "count": "2707" }, {
      "value": "Climate change",
      "count": "2679",
    }, { "value": "Depression", "count": "2654" }, { "value": "HIV", "count": "2378" }, {
      "value": "Children",
      "count": "2167",
    }, { "value": "Education", "count": "2153" }, {
      "value": "Machine learning",
      "count": "2109",
    }, { "value": "Systematic review", "count": "2009" }, {
      "value": "Social media",
      "count": "2001",
    }, { "value": "Breast cancer", "count": "1966" }, {
      "value": "Virtual reality",
      "count": "1819",
    }, { "value": "Mental health", "count": "1775" }, {
      "value": "Cloud computing",
      "count": "1693",
    }, { "value": "Sustainability", "count": "1643" }, {
      "value": "Meta-analysis",
      "count": "1640",
    }, { "value": "Epidemiology", "count": "1522" }, { "value": "Cancer", "count": "1504" }, {
      "value": "Obesity",
      "count": "1471",
    }, { "value": "Adolescents", "count": "1446" }, { "value": "Big data", "count": "1432" }],
  }, {
    "name": "pub",
    "values": [{ "value": "Scientific Reports", "count": "10620" }, {
      "value": "BMC Public Health",
      "count": "6492",
    }, { "value": "BMC Health Services Research", "count": "4771" }, {
      "value": "Trials",
      "count": "3258",
    }, { "value": "Nature Communications", "count": "2922" }, {
      "value": "Nature",
      "count": "2714",
    }, { "value": "BMC Cancer", "count": "2635" }, {
      "value": "Multimedia Tools and Applications",
      "count": "2358",
    }, { "value": "BMC Infectious Diseases", "count": "2097" }, {
      "value": "BMC Psychiatry",
      "count": "1986",
    }, { "value": "AIDS and Behavior", "count": "1969" }, {
      "value": "Malaria Journal",
      "count": "1904",
    }, { "value": "Wireless Personal Communications", "count": "1807" }, {
      "value": "BMC Musculoskeletal Disorders",
      "count": "1780",
    }, { "value": "BMC Genomics", "count": "1707" }, {
      "value": "BMC Research Notes",
      "count": "1644",
    }, { "value": "Neuropsychopharmacology", "count": "1574" }, {
      "value": "BMC Pregnancy and Childbirth",
      "count": "1546",
    }, { "value": "BMC Medical Education", "count": "1545" }, { "value": "BMC Bioinformatics", "count": "1506" }],
  }, {
    "name": "year",
    "values": [{ "value": "2021", "count": "203" }, { "value": "2020", "count": "26286" }, {
      "value": "2019",
      "count": "78922",
    }, { "value": "2018", "count": "66798" }, { "value": "2017", "count": "61732" }, {
      "value": "2016",
      "count": "58249",
    }, { "value": "2015", "count": "46535" }, { "value": "2014", "count": "46434" }, {
      "value": "2013",
      "count": "38493",
    }, { "value": "2012", "count": "28194" }, { "value": "2011", "count": "24444" }, {
      "value": "2010",
      "count": "19290",
    }, { "value": "2009", "count": "15423" }, { "value": "2008", "count": "12165" }, {
      "value": "2007",
      "count": "9477",
    }, { "value": "2006", "count": "7171" }, { "value": "2005", "count": "5149" }, {
      "value": "2004",
      "count": "4081",
    }, { "value": "2003", "count": "2979" }, { "value": "2002", "count": "2058" }],
  }, {
    "name": "country",
    "values": [{ "value": "United States", "count": "165151" }, {
      "value": "United Kingdom",
      "count": "68010",
    }, { "value": "Germany", "count": "53556" }, { "value": "China", "count": "43848" }, {
      "value": "Canada",
      "count": "32983",
    }, { "value": "Australia", "count": "32493" }, { "value": "Italy", "count": "30225" }, {
      "value": "Netherlands",
      "count": "25664",
    }, { "value": "France", "count": "23582" }, { "value": "Spain", "count": "20123" }, {
      "value": "India",
      "count": "19301",
    }, { "value": "Japan", "count": "18428" }, { "value": "Switzerland", "count": "15845" }, {
      "value": "Sweden",
      "count": "14815",
    }, { "value": "Brazil", "count": "10513" }, { "value": "Belgium", "count": "10197" }, {
      "value": "South Korea",
      "count": "10191",
    }, { "value": "Denmark", "count": "9607" }, { "value": "Norway", "count": "9361" }, {
      "value": "Austria",
      "count": "9271",
    }],
  }, { "name": "type", "values": [{ "value": "Journal", "count": "349895" }, { "value": "Book", "count": "216955" }] }],
};
